# Generated by Django 4.1.5 on 2023-02-05 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name (User)')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date_created')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('extension', models.IntegerField(verbose_name='Extension')),
                ('department', models.CharField(max_length=255, verbose_name='Department')),
                ('category', models.CharField(choices=[('Network', 'Network'), ('Printer', 'Printer'), ('Computer', 'Computer'), ('Software', 'Software'), ('Data/Files', 'Data/Files')], default='Network', max_length=120)),
                ('summary', models.TextField(max_length=255, verbose_name='Summary/Issue')),
                ('solution', models.TextField(default='', max_length=500, verbose_name='Solution/Remarks')),
                ('status', models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Review', 'Review')], default='New', max_length=120)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=120)),
                ('owner', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tasks',
                'db_table': 'support',
            },
        ),
    ]
