# Generated by Django 4.0.6 on 2022-07-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_support_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='Assigned',
        ),
        migrations.RemoveField(
            model_name='support',
            name='extention',
        ),
        migrations.AddField(
            model_name='support',
            name='assigned',
            field=models.CharField(default='John', max_length=255, verbose_name='ICT Officer name'),
        ),
        migrations.AddField(
            model_name='support',
            name='extension',
            field=models.CharField(default='43213', max_length=255),
        ),
        migrations.AlterField(
            model_name='support',
            name='department',
            field=models.CharField(max_length=255, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='support',
            name='name',
            field=models.CharField(max_length=255, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='support',
            name='summary',
            field=models.TextField(max_length=255, verbose_name='Summary'),
        ),
    ]
