# Generated by Django 4.1.5 on 2023-02-12 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_support_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='support',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
