# Generated by Django 4.0.6 on 2022-07-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_remove_support_assigned_remove_support_extention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='assigned',
            field=models.CharField(max_length=255, verbose_name='ICT Officer name'),
        ),
        migrations.AlterField(
            model_name='support',
            name='extension',
            field=models.CharField(max_length=255),
        ),
    ]
