# Generated by Django 4.1.5 on 2023-02-12 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0003_remove_support_assigned_to_support_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='support',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
