# Generated by Django 4.0.6 on 2022-07-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_support_assigned_alter_support_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='extension',
            field=models.IntegerField(max_length=255),
        ),
    ]
