# Generated by Django 4.0.6 on 2022-07-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_support_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='category',
            field=models.CharField(choices=[('1', 'Network'), ('2', 'Printer'), ('3', 'Computer'), ('4', 'CCTV'), ('5', 'Software'), ('6', 'Data/Files')], default=1, max_length=24),
        ),
        migrations.AlterField(
            model_name='support',
            name='assigned',
            field=models.CharField(max_length=255, verbose_name='Assigned To(ICT Officer/Casual/Intern)'),
        ),
        migrations.AlterField(
            model_name='support',
            name='department',
            field=models.CharField(max_length=255, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='support',
            name='extension',
            field=models.IntegerField(verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='support',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name (User)'),
        ),
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Completed'), (3, 'Archived')], default='1'),
        ),
        migrations.AlterField(
            model_name='support',
            name='summary',
            field=models.TextField(max_length=255, verbose_name='Summary/Issue'),
        ),
    ]
