# Generated by Django 4.0.6 on 2022-07-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_support_category_alter_support_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='solution',
            field=models.TextField(default='Not provided', max_length=500, verbose_name='Solution/Remarks'),
        ),
    ]
