# Generated by Django 4.0.6 on 2022-07-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_support_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='solution',
            field=models.TextField(default='', max_length=500, verbose_name='Solution/Remarks'),
        ),
    ]
