# Generated by Django 4.0.6 on 2022-07-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_alter_support_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='category',
            field=models.CharField(choices=[('Network', 'Network'), ('Printer', 'Printer'), ('Computer', 'Computer'), ('CCTV', 'Cctv'), ('Software', 'Software'), ('Data/Files', 'Data')], default=1, max_length=24),
        ),
    ]
