# Generated by Django 4.0.6 on 2022-07-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_alter_support_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='category',
            field=models.CharField(choices=[('1', 'Network'), ('2', 'Printer'), ('3', 'Computer'), ('4', 'CCTV'), ('5', 'Software'), ('6', 'Data/Files')], default=1, max_length=24),
        ),
    ]
