# Generated by Django 4.0.6 on 2022-07-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_alter_support_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Completed'), (3, 'Review')], default='1'),
        ),
    ]
