# Generated by Django 4.0.6 on 2022-07-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_alter_support_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='category',
            field=models.CharField(choices=[('NETWORK', 'Network'), ('PRINTER', 'Printer'), ('COMPUTER', 'Computer'), ('CCTV', 'CCTV'), ('SOFTWARE', 'Software'), ('Data', 'Data/Files')], default=1, max_length=24),
        ),
        migrations.AlterField(
            model_name='support',
            name='solution',
            field=models.TextField(default='NETWORK', max_length=500, verbose_name='Solution/Remarks'),
        ),
    ]
