# Generated by Django 4.0.6 on 2022-07-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_alter_support_options_alter_support_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='support',
            table='support',
        ),
    ]
