# Generated by Django 4.0.6 on 2022-07-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0018_support_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='manager',
        ),
    ]
