# Generated by Django 4.0.6 on 2022-07-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0019_remove_support_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Review', 'Review')], default='New', max_length=120),
        ),
    ]
