# Generated by Django 4.0.6 on 2022-07-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0020_alter_support_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='category',
            field=models.CharField(choices=[('Network', 'Network'), ('Printer', 'Printer'), ('CCTV', 'CCTV'), ('Software', 'Software'), ('Data/Files', 'Data/Files')], default='Network', max_length=120),
        ),
    ]
