# Generated by Django 4.0.6 on 2022-07-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0023_alter_support_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Review', 'Review')], default='New', max_length=120),
        ),
    ]
