# Generated by Django 4.0.6 on 2022-07-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0024_alter_support_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='date_created',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Date'),
        ),
    ]
