# Generated by Django 4.0.6 on 2022-07-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0025_alter_support_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='category',
            field=models.CharField(choices=[('Network', 'Network'), ('Printer', 'Printer'), ('Computer', 'Computer'), ('Software', 'Software'), ('Data/Files', 'Data/Files')], default='Network', max_length=120),
        ),
    ]
