# Generated by Django 4.0.6 on 2022-07-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0026_alter_support_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
    ]
