# Generated by Django 4.0.6 on 2022-08-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0027_alter_support_date_created'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='support',
            table='task_monitor',
        ),
    ]
