# Generated by Django 4.0.6 on 2022-08-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0028_alter_support_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='support',
            table='support',
        ),
    ]
