# Generated by Django 4.0.6 on 2022-08-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0031_support_date_modified_alter_support_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='support',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date_created'),
        ),
    ]
