# Generated by Django 4.0.6 on 2022-08-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0032_rename_user_support_owner_alter_support_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=120),
        ),
    ]
