# Generated by Django 4.0.6 on 2022-08-16 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0033_support_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='assigned',
        ),
    ]
