# Generated by Django 4.0.6 on 2022-08-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='staff',
            new_name='user',
        ),
    ]
