# Generated by Django 4.0.6 on 2022-08-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_rename_user_profile_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='owner',
            new_name='user',
        ),
    ]
